DROP TABLE IF EXISTS items;

CREATE TABLE items (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	pot_id INTEGER NOT NULL,
	description VARCHAR NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	amount INTEGER NOT NULL,
	paidby VARCHAR NOT NULL,
	FOREIGN KEY (pot_id) REFERENCES pots (p_id)
);
